version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=rtdatabase.cfoay2c6o63s.eu-central-1.rds.amazonaws.com,1433;Database=BrainBay;User Id=admin;Password=brainBay123;TrustServerCertificate=True;
